name: Check and Update Client Portal

on:
  schedule:
    - cron: "0 5 * * *" # Every morning at 5.00 AM
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run update checker
      run: node scripts/update_checker.js

    - name: Commit changes
      run: |
        git config --local user.email "demircancelebi+ibkr@gmail.com"
        git config --local user.name "GitHub Action for IBKR"
        git add clientportal
        git commit -m "Update Client Portal" -a || echo "No changes to commit"
        git push